FROM bitnami/node

ARG APP_NAME
ENV DEBIAN_FRONTEND=noninteractive
ENV APP_NAME=${APP_NAME}
#ENV APP_NAME=caca

WORKDIR /app
COPY . /app

RUN apt update && \
    apt install -y curl netcat-openbsd && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g @angular/cli
#    dothat in Makefile: ng new ${APP_NAME}

CMD ["tail", "-f", "/dev/null"]
