# Use bitnami Java image as base
FROM bitnami/java

# Build arguments
ARG DOCKER_BACKEND_WORKDIR

# Configure noninteractive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
RUN apt update && \
    apt install -y curl maven unzip zip netcat-openbsd && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Install SDKMAN and Spring Boot CLI
ENV SDKMAN_DIR="/root/.sdkman"
RUN set -e && \
    curl -s "https://get.sdkman.io" | bash && \
    bash -c "source $SDKMAN_DIR/bin/sdkman-init.sh && \
    yes | sdk install springboot"

# Add Spring Boot to PATH
ENV PATH="$SDKMAN_DIR/candidates/springboot/current/bin:${PATH}"

# Set working directory
WORKDIR ${DOCKER_BACKEND_WORKDIR}

# Copy your application files
COPY . ${DOCKER_BACKEND_WORKDIR}

# Verify Spring Boot CLI installation
RUN spring --version

# The command to create a new Spring Boot project
# CMD ["mvn", "clean", "spring-boot:run"]
CMD ["tail", "-f", "/dev/null"]
